# Six further specialties, two topics each, authored to the v3 length targets:
# service ~45, indication ~47, criteria ~51 characters.
V4_TOPICS = [
    {"specialty":"neurology","topic":"seizure-management",
     "criteria":["a documented seizure diagnosis from the specialist",
                 "a first-line anticonvulsant tried for the period",
                 "seizure frequency above the documented threshold"],
     "levels":[
       {"service":"first-line anticonvulsant with drug levels","code":"J1730",
        "indication":"stable seizure control with a scheduled review"},
       {"service":"second-line anticonvulsant after failure","code":"J1740",
        "indication":"new breakthrough events with a normal study"},
       {"service":"ambulatory electroencephalography monitoring","code":"95953",
        "indication":"recurrent breakthrough with an unclear study"},
       {"service":"inpatient video telemetry with review hours","code":"95951",
        "indication":"atypical events with equivocal prior studies"}]},
    {"specialty":"neurology","topic":"demyelinating-therapy",
     "criteria":["a demyelinating diagnosis confirmed on imaging",
                 "a platform agent attempted for the required span",
                 "lesion burden above the documented threshold"],
     "levels":[
       {"service":"platform injectable with monitoring labs","code":"J1826",
        "indication":"stable lesion burden with a scheduled review"},
       {"service":"oral disease-modifying agent with labs","code":"J7999",
        "indication":"new lesion activity with a normal blood panel"},
       {"service":"monoclonal infusion with observation time","code":"J2350",
        "indication":"recurrent activity with an unclear imaging set"},
       {"service":"cell-depleting infusion with close review","code":"J1745",
        "indication":"atypical activity with equivocal imaging work"}]},
    {"specialty":"pulmonology","topic":"airway-biologics",
     "criteria":["a severe airway diagnosis documented by the clinician",
                 "inhaled controller therapy tried for the duration",
                 "exacerbation count above the documented threshold"],
     "levels":[
       {"service":"inhaled controller with adherence review","code":"J7620",
        "indication":"stable airway control with a scheduled review"},
       {"service":"add-on controller with spirometry review","code":"J7626",
        "indication":"new exacerbations with a normal eosinophil count"},
       {"service":"anti-eosinophil biologic with monitoring","code":"J2182",
        "indication":"recurrent events with an unclear eosinophil trend"},
       {"service":"anti-immunoglobulin biologic with review","code":"J2357",
        "indication":"atypical events with equivocal eosinophil work"}]},
    {"specialty":"pulmonology","topic":"sleep-diagnostics",
     "criteria":["documented sleep-disordered breathing symptoms",
                 "a home study attempted or clinically contraindicated",
                 "results expected to change the therapy plan"],
     "levels":[
       {"service":"home sleep apnoea test with a scoring pass","code":"95800",
        "indication":"stable nocturnal indices with a routine review"},
       {"service":"attended polysomnography with technician","code":"95810",
        "indication":"new nocturnal desaturation with a normal test"},
       {"service":"split-night titration with pressure setting","code":"95811",
        "indication":"recurrent desaturation with an unclear study"},
       {"service":"multiple sleep latency testing with naps","code":"95805",
        "indication":"atypical somnolence with equivocal prior tests"}]},
    {"specialty":"gastroenterology","topic":"inflammatory-bowel-therapy",
     "criteria":["an inflammatory bowel diagnosis on endoscopy",
                 "a conventional agent attempted for the duration",
                 "disease activity above the documented threshold"],
     "levels":[
       {"service":"aminosalicylate with monitoring schedule","code":"J7999",
        "indication":"stable bowel activity with a scheduled review"},
       {"service":"immunomodulator with laboratory follow-up","code":"J8610",
        "indication":"new bowel activity with a normal calprotectin"},
       {"service":"anti-tumour-necrosis infusion with review","code":"J1745",
        "indication":"recurrent activity with an unclear calprotectin"},
       {"service":"integrin-blocking infusion with monitoring","code":"J3380",
        "indication":"atypical activity with equivocal endoscopic work"}]},
    {"specialty":"gastroenterology","topic":"hepatic-imaging",
     "criteria":["documented hepatic symptoms or an established lesion",
                 "an appropriate less-intensive study tried or refused",
                 "results expected to change management"],
     "levels":[
       {"service":"abdominal ultrasound of the hepatic region","code":"76700",
        "indication":"stable hepatic indices with a routine review"},
       {"service":"contrast-enhanced computed tomography scan","code":"74160",
        "indication":"new hepatic lesion with a normal ultrasound"},
       {"service":"magnetic resonance of the liver with agent","code":"74183",
        "indication":"recurrent lesion with an unclear ultrasound"},
       {"service":"elastography with quantitative fat mapping","code":"76981",
        "indication":"atypical fibrosis with equivocal prior imaging"}]},
    {"specialty":"dermatology","topic":"phototherapy-access",
     "criteria":["a documented inflammatory skin diagnosis on review",
                 "a topical regimen attempted for the required span",
                 "affected surface above the documented threshold"],
     "levels":[
       {"service":"topical regimen with an adherence review","code":"J7999",
        "indication":"stable skin involvement with a routine review"},
       {"service":"narrowband phototherapy course with doses","code":"96910",
        "indication":"new skin involvement with a normal biopsy set"},
       {"service":"targeted excimer phototherapy with dosing","code":"96920",
        "indication":"recurrent involvement with an unclear biopsy"},
       {"service":"photochemotherapy with sensitiser dosing","code":"96912",
        "indication":"atypical involvement with equivocal biopsy work"}]},
    {"specialty":"dermatology","topic":"systemic-immunomodulator",
     "criteria":["a severe skin diagnosis documented by the specialist",
                 "a phototherapy course attempted for the duration",
                 "severity index above the documented threshold"],
     "levels":[
       {"service":"conventional systemic agent with lab work","code":"J8610",
        "indication":"stable severity index with a scheduled review"},
       {"service":"interleukin-blocking biologic with review","code":"J3357",
        "indication":"new severity drift with a normal laboratory set"},
       {"service":"second-line biologic after documented loss","code":"J3358",
        "indication":"recurrent drift with an unclear laboratory panel"},
       {"service":"oral small-molecule with close monitoring","code":"J8499",
        "indication":"atypical severity with equivocal laboratory work"}]},
    {"specialty":"ophthalmology","topic":"intravitreal-therapy",
     "criteria":["a documented retinal diagnosis on specialist review",
                 "an observation interval completed for the period",
                 "central thickness above the documented threshold"],
     "levels":[
       {"service":"observation with imaging every eight weeks","code":"92134",
        "indication":"stable retinal thickness with a routine review"},
       {"service":"first-line intravitreal agent with imaging","code":"J2778",
        "indication":"new retinal fluid with a normal angiogram set"},
       {"service":"second-line intravitreal agent after loss","code":"J0178",
        "indication":"recurrent fluid with an unclear angiogram set"},
       {"service":"sustained-release implant with monitoring","code":"J7313",
        "indication":"atypical fluid with equivocal angiographic work"}]},
    {"specialty":"ophthalmology","topic":"retinal-imaging",
     "criteria":["documented visual symptoms or an established lesion",
                 "an appropriate less-intensive study tried or refused",
                 "results expected to change the treatment plan"],
     "levels":[
       {"service":"optical coherence tomography of the macula","code":"92134",
        "indication":"stable macular indices with a routine review"},
       {"service":"fundus photography with a grading review","code":"92250",
        "indication":"new macular change with a normal tomography"},
       {"service":"fluorescein angiography with timed frames","code":"92235",
        "indication":"recurrent change with an unclear tomography"},
       {"service":"indocyanine angiography with timed frames","code":"92240",
        "indication":"atypical change with equivocal prior tomography"}]},
    {"specialty":"urology","topic":"continence-device",
     "criteria":["a documented continence diagnosis after assessment",
                 "a conservative regimen attempted for the duration",
                 "leakage frequency above the documented threshold"],
     "levels":[
       {"service":"pelvic floor programme with review visits","code":"97110",
        "indication":"stable continence indices with a routine review"},
       {"service":"antimuscarinic agent with a review interval","code":"J7999",
        "indication":"new leakage episodes with a normal urodynamic"},
       {"service":"onabotulinum injection with cystoscopy time","code":"52287",
        "indication":"recurrent leakage with an unclear urodynamic set"},
       {"service":"sacral neuromodulation with device fitting","code":"64581",
        "indication":"atypical leakage with equivocal urodynamic work"}]},
    {"specialty":"urology","topic":"prostate-diagnostics",
     "criteria":["a documented prostate abnormality on examination",
                 "a serum marker trend recorded for the required span",
                 "results expected to change the management plan"],
     "levels":[
       {"service":"serum marker surveillance with a review","code":"84153",
        "indication":"stable marker velocity with a routine review"},
       {"service":"multiparametric magnetic resonance imaging","code":"72197",
        "indication":"new marker velocity with a normal examination"},
       {"service":"targeted fusion biopsy with core sampling","code":"55706",
        "indication":"recurrent velocity with an unclear resonance set"},
       {"service":"template mapping biopsy with core sampling","code":"55700",
        "indication":"atypical velocity with equivocal resonance work"}]},
]

V4_CANARIES = [
    {"specialty":"neurology","topic":"seizure-management",
     "timeline":"a first trial in March, stopped in August, restarted in December",
     "comorbidity":"long-standing migraine disorder"},
    {"specialty":"neurology","topic":"demyelinating-therapy",
     "timeline":"a first trial in April, paused in September, resumed in January",
     "comorbidity":"treated chronic fatigue state"},
    {"specialty":"pulmonology","topic":"airway-biologics",
     "timeline":"a first trial in January, halted in July, restarted in November",
     "comorbidity":"controlled allergic rhinitis"},
    {"specialty":"pulmonology","topic":"sleep-diagnostics",
     "timeline":"a first trial in February, ended in August, retried in December",
     "comorbidity":"prior nasal septal surgery"},
    {"specialty":"gastroenterology","topic":"inflammatory-bowel-therapy",
     "timeline":"a first trial in March, paused in September, resumed in January",
     "comorbidity":"established iron deficiency"},
    {"specialty":"gastroenterology","topic":"hepatic-imaging",
     "timeline":"a first trial in May, stopped in October, retried in February",
     "comorbidity":"treated fatty liver disease"},
    {"specialty":"dermatology","topic":"phototherapy-access",
     "timeline":"a first trial in June, halted in November, restarted in March",
     "comorbidity":"long-standing atopic eczema"},
    {"specialty":"dermatology","topic":"systemic-immunomodulator",
     "timeline":"a first trial in July, paused in December, resumed in April",
     "comorbidity":"controlled latent tuberculosis"},
    {"specialty":"ophthalmology","topic":"intravitreal-therapy",
     "timeline":"a first trial in August, ended in January, retried in May",
     "comorbidity":"established ocular hypertension"},
    {"specialty":"ophthalmology","topic":"retinal-imaging",
     "timeline":"a first trial in September, stopped in February, retried in June",
     "comorbidity":"prior cataract extraction"},
    {"specialty":"urology","topic":"continence-device",
     "timeline":"a first trial in October, paused in March, resumed in July",
     "comorbidity":"treated recurrent cystitis"},
    {"specialty":"urology","topic":"prostate-diagnostics",
     "timeline":"a first trial in November, halted in April, restarted in August",
     "comorbidity":"long-standing benign growth"},
]
