#!/usr/bin/env python3
r"""The announcement experiment: a control-flow intervention, and a caveat.

Why it exists. The depth sweep of Appendix~\ref{app:depth} varies the pass cap,
and the cap is announced in the extraction prompt, so the sweep's arms differ in
what the model is told as well as in how deep it may go. The clean version of
that sweep therefore omits the announcement -- which leaves the taxonomy's
evidence in a different prompt regime from the headline arm. This script measures
whether that gap matters, by re-running the headline corpus's undefended arm with
the announcement removed and nothing else changed.

It answers two questions and the answers point in opposite directions, which is
why both are reported.

*Is the headline comparable to the sweep?* No. Membership moves by roughly the
size of the whole padding effect, so the two regimes are not interchangeable and
the headline figures are specific to a configuration that announces the budget.
That is a limitation, and \S\ref{sec:limits} states it.

*Does the taxonomy predict what moves?* Yes, and this is the cleanest test of it
in the paper. Removing the announcement is a control-flow intervention: it changes
what the agent knows about its own budget, not what it discloses about the data.
Membership, which the taxonomy calls control-flow-carried, moves, and so does its
named carrier. The attribute's provider-chosen carrier does not.

Run:  python3 scripts/make_iclr_announce.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from make_paper_artifacts import (  # noqa: E402
    _records_for,
    assert_macro_names_are_latex_safe,
)
from traceguard.attack import evaluate_attack, observability_transform  # noqa: E402

CELLS = [
    ("Attr", "attribute", None),
    ("Memb", "membership", None),
    ("MembTiming", "membership", "timing_only"),
    ("AttrIngress", "attribute", "ingress_only"),
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--announced", type=Path, default=ROOT / "artifacts" / "cvm-honest.jsonl")
    ap.add_argument("--quiet", type=Path,
                    default=ROOT / "artifacts" / "w5" / "w5-quiet-adaptive.jsonl")
    ap.add_argument("--condition", default="adaptive")
    ap.add_argument("--seed", type=int, default=20260710)
    ap.add_argument("--report", type=Path,
                    default=ROOT / "iclr2027" / "tables" / "announce-report.json")
    ap.add_argument("--macros", type=Path,
                    default=ROOT / "iclr2027" / "tables" / "macros_announce.tex")
    args = ap.parse_args()

    arms = {}
    for name, path in (("announced", args.announced), ("quiet", args.quiet)):
        rows = [json.loads(l) for l in path.read_text().splitlines() if l.strip()]
        arms[name] = _records_for(rows, args.condition)
        if not arms[name]:
            raise SystemExit(f"no {args.condition} records in {path}")

    macros: dict[str, str] = {
        "annNAnnounced": str(len(arms["announced"])),
        "annNQuiet": str(len(arms["quiet"])),
    }
    report: dict[str, object] = {"seed": args.seed, "condition": args.condition,
                                 "announced_journal": str(args.announced),
                                 "quiet_journal": str(args.quiet), "cells": {}}
    print(f"  {'measurement':26} {'announced':>10} {'quiet':>8} {'delta':>8}")
    for tag, target, vantage in CELLS:
        vals = {}
        for name in ("announced", "quiet"):
            kw = {} if vantage is None else {
                "feature_transform": observability_transform(vantage)}
            vals[name] = evaluate_attack(
                arms[name], target=target, n_bootstrap=0, seed=args.seed, **kw)["auc"]
        delta = vals["quiet"] - vals["announced"]
        label = target if vantage is None else f"{target} ({vantage})"
        report["cells"][label] = {**vals, "delta": delta}
        macros[f"ann{tag}Announced"] = f"{vals['announced']:.3f}"
        macros[f"ann{tag}Quiet"] = f"{vals['quiet']:.3f}"
        macros[f"ann{tag}Delta"] = f"{delta:+.3f}"
        print(f"  {label:26} {vals['announced']:>10.3f} {vals['quiet']:>8.3f} {delta:>+8.3f}")
    assert_macro_names_are_latex_safe(list(macros))

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.macros.write_text(
        "% The announcement experiment: the headline corpus's undefended arm with\n"
        "% the pass budget removed from the prompt and nothing else changed.\n"
        "% Generated by scripts/make_iclr_announce.py. ICLR-scoped.\n"
        + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items()))
    print(f"\nwrote {args.report}\nwrote {args.macros}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
