#!/usr/bin/env python3
"""Turn the matrix journals into the paper's per-factor tables and macros.

One table per reviewer ask -- graded sensitivity, autonomy, architecture, crew
model -- each reporting its numbers against *its own* calibrated permutation
null rather than against 0.5, because the protocol's floor sits near 0.57 and a
bare AUC is not interpretable without it.

House style, applied throughout: report a trend or a paired difference rather
than a bare point estimate; report both estimators where they disagree; and say
plainly what the evidence does not support. Three crew deployments cannot
support a scaling law and this script does not pretend otherwise -- it reports
an ordering and one pre-declared contrast.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from make_paper_artifacts import (  # noqa: E402
    _auc2,
    _auc3,
    _records_for,
    _wrap,
    format_p_value,
    merge_macros,
)

from traceguard.attack import (  # noqa: E402
    PUBLISHED_DEPTH_RANGE,
    evaluate_attack,
    evaluate_ordinal_leakage,
    holm_bonferroni,
    paired_group_difference,
    permutation_null,
    randomized_response_frontier,
)
from traceguard.attack import extract_trace_features as _features  # noqa: E402
from traceguard.experiment import load_experiment_records  # noqa: E402

STAR_EXCLUDED_JOURNALS = frozenset({"matrix-cvm.jsonl"})

MACRO_HEADER = (
    "% Generated by scripts/make_matrix_artifacts.py -- do not edit by hand.\n"
    "% Numbers come from artifacts/matrix-*.jsonl; regenerate with `make paper-matrix`.\n"
)
TABLE_HEADER = "% Generated by scripts/make_matrix_artifacts.py from the matrix journals.\n"

# Deployment order is fixed here rather than discovered, so a missing arm shows
# up as a dash in the table instead of silently vanishing from the comparison.
CREW_DEPLOYMENTS = ("gpt-4o", "gpt-5.6-luna", "gpt-5.6-sol")


def _by_model(records: list[dict[str, Any]], deployment: str) -> list[dict[str, Any]]:
    """Records whose whole crew ran on one deployment.

    A cell with a mixed crew belongs to no single model arm, so it is excluded
    rather than attributed to whichever deployment happens to appear first.
    """

    out = []
    for record in records:
        models = (record.get("provenance") or {}).get("models") or {}
        if models and set(models.values()) == {deployment}:
            out.append(record)
    return out


def _measure(
    records: list[dict[str, Any]], *, target: str, seed: int, n_perm: int
) -> dict[str, Any] | None:
    """Attack AUC plus this arm's own null, or None when the arm is unevaluable."""

    if len(records) < 8:
        return None
    try:
        report = evaluate_attack(records, target=target, n_bootstrap=0, seed=seed)
    except ValueError:
        return None
    row: dict[str, Any] = {
        "n": len(records),
        "auc": report["auc"],
        "pooled_auc": report["pooled_auc"],
        "n_groups": report.get("n_groups"),
        "n_groups_skipped": report.get("n_groups_skipped", 0),
    }
    if n_perm:
        try:
            null = permutation_null(
                records, target=target, n_perm=n_perm, within_group=True, seed=seed + 505
            )
        except ValueError:
            return row
        row["null_mean"] = null["null_mean"]
        row["null_q95"] = null.get("null_q95")
        row["p_value"] = null["p_value"]
        row["n_perm"] = null["n_perm"]
    return row


def _combined_factor_table(
    groups: list[tuple[str, list[tuple[str, dict[str, Any] | None, dict[str, Any] | None]]]],
) -> str:
    """All three swept factors in one float.

    They share identical columns, and three separate table floats cost roughly a
    page of a page-limited paper for no information the reader does not get from
    a grouped one. The graded-sensitivity table stays separate because its
    columns are genuinely different -- it publishes the mechanism, not an AUC.
    """

    body = []
    for index, (factor, rows) in enumerate(groups):
        if index:
            body.append("\\addlinespace[2pt]")
        for position, (label, attr, memb) in enumerate(rows):
            cells = []
            for row in (attr, memb):
                if row is None:
                    cells.extend(["--", "--"])
                    continue
                sig = f"$p{format_p_value(row)}$" if "p_value" in row else "--"
                cells.extend([f"{_auc3(row['auc'])} ({_auc2(row.get('null_mean'))})", sig])
            n = (attr or memb or {}).get("n", "--")
            head = f"\\emph{{{factor}}}" if position == 0 else ""
            body.append(f"{head} & {label} & {n} & " + " & ".join(cells) + " \\\\")
    header = (
        "Factor & Arm & $n$ & \\multicolumn{2}{c}{Attribute} & "
        "\\multicolumn{2}{c}{Membership} \\\\\n"
        "  &  &  & AUC (null) & sig. & AUC (null) & sig. \\\\\n"
    )
    return _wrap(3, "llrcccc", header, "\n".join(body))


def _factor_table(
    caption_label: str,
    rows: list[tuple[str, dict[str, Any] | None, dict[str, Any] | None]],
) -> str:
    """One row per arm, reporting both secrets against their own nulls.

    Both targets are shown because on the autonomy axis they move in opposite
    directions -- lowering autonomy raises attribute leakage and lowers
    membership leakage -- and a table carrying only the attribute column would
    present "less autonomy leaks more" as the whole finding.
    """

    body = []
    for label, attr, memb in rows:
        cells = []
        for row in (attr, memb):
            if row is None:
                cells.extend(["--", "--"])
                continue
            p_cell = f"$p{format_p_value(row)}$" if "p_value" in row else "--"
            cells.extend([f"{_auc3(row['auc'])} ({_auc2(row.get('null_mean'))})", p_cell])
        n = (attr or memb or {}).get("n", "--")
        body.append(f"{label} & {n} & " + " & ".join(cells) + " \\\\")
    header = (
        f"{caption_label} & $n$ & \\multicolumn{{2}}{{c}}{{Attribute}} & "
        "\\multicolumn{2}{c}{Membership} \\\\\n"
        "  &  & AUC (null) & sig. & AUC (null) & sig. \\\\\n"
    )
    return _wrap(4, "lrcccc", header, "\n".join(body))


def _rung_mechanism(records: list[dict[str, Any]]) -> dict[int, dict[str, float]]:
    """Median research depth and total egress per rung.

    Published alongside the attacker score because the ordinal result is a claim
    about a mechanism, and a reader should be able to see the mechanism rather
    than take the AUC's word for it. Depth and egress are the two coordinates the
    ablation identifies as load-bearing.
    """

    per: dict[int, dict[str, list[float]]] = {}
    for record in records:
        rung = int(record.get("sensitivity_level", 0))
        steps = (record.get("trace") or {}).get("steps") or []
        depth = sum(
            1
            for step in steps
            if any(
                token in str(step.get("step_type", "")).lower()
                for token in ("retriev", "extraction")
            )
        )
        egress = sum(int(step.get("egress_bytes") or 0) for step in steps)
        bucket = per.setdefault(rung, {"depth": [], "egress": []})
        bucket["depth"].append(depth)
        bucket["egress"].append(egress)
    return {
        rung: {
            "depth": statistics.median(values["depth"]),
            "egress": statistics.median(values["egress"]),
        }
        for rung, values in sorted(per.items())
        if values["depth"]
    }


def _grade_table(
    ordinal: dict[str, Any] | None, mechanism: dict[int, dict[str, float]]
) -> str:
    """Per-rung attacker score next to the two coordinates that produce it.

    The full-ladder statistic is deliberately *not* the headline: it is large
    whenever the attacker separates rung 0 from the rest, so it restates the
    binary result. The incremental claim lives in the within-sensitive trend, and
    the depth/egress columns let a reader see whether the ladder is ordered or
    merely thresholded.
    """

    if not ordinal or "rungs" not in ordinal:
        return TABLE_HEADER + "% no graded journal available\n"
    body = []
    for rung, size, mean in zip(
        ordinal["rungs"], ordinal["rung_sizes"], ordinal["rung_mean_score"], strict=True
    ):
        mech = mechanism.get(rung)
        depth = f"{mech['depth']:.0f}" if mech else "--"
        egress = f"{mech['egress']:.0f}" if mech else "--"
        body.append(f"L{rung} & {size} & {mean:.3f} & {depth} & {egress} \\\\")
    header = (
        "Rung & $n$ & Attacker & Depth & Egress \\\\\n"
        "     &      & score    & (med.) & (med.\\,B) \\\\\n"
    )
    return _wrap(6, "lrrrr", header, "\n".join(body))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--journal-dir", type=Path, default=ROOT / "artifacts")
    ap.add_argument("--out-dir", type=Path, default=ROOT / "tables")
    ap.add_argument("--seed", type=int, default=20260710)
    ap.add_argument(
        "--permutations",
        type=int,
        default=400,
        help="within-group label permutations per arm (0 disables the nulls)",
    )
    ap.add_argument("--report", type=Path, default=None, help="also dump the full JSON here")
    args = ap.parse_args(argv)

    def load(spoke: str) -> list[dict[str, Any]]:
        path = args.journal_dir / f"matrix-{spoke}.jsonl"
        if not path.is_file():
            print(f"  (no {path.name}; that spoke's rows will read as --)")
            return []
        return load_experiment_records(path)

    baseline = load("baseline")
    if not baseline:
        raise SystemExit(
            "no artifacts/matrix-baseline.jsonl; run scripts/run_experiment_matrix.py first"
        )

    macros: dict[str, str] = {}
    tables: dict[str, str] = {}
    report: dict[str, Any] = {"seed": args.seed, "permutations": args.permutations}
    # One pre-declared family, fixed before the runs. Declaring it here rather
    # than after seeing which arms came out well is the whole point of Holm.
    family: dict[str, float] = {}

    def measure(
        records: list[dict[str, Any]],
    ) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
        return (
            _measure(records, target="attribute", seed=args.seed, n_perm=args.permutations),
            _measure(records, target="membership", seed=args.seed, n_perm=args.permutations),
        )

    adaptive = _records_for(baseline, "adaptive")
    structure = _records_for(baseline, "structure")

    # ------------------------------------------------- corpus confound audit --
    # Cited by the graded-sensitivity paragraph. Generated rather than quoted,
    # because a length confound reintroduced by a corpus edit would otherwise be
    # contradicted only by a comment.
    try:
        from gen_pa_corpus import length_channel_recoverability

        corpus = json.loads(
            (ROOT / "src/traceguard/data/synthetic-medical-v2.json").read_text()
        )
        audit = length_channel_recoverability(corpus)
        report["length_audit"] = audit
        macros["gradeLengthRecovery"] = f"{audit['recoverability'] * 100:.1f}"
        macros["gradeChance"] = f"{audit['chance'] * 100:.0f}"
        macros["gradeLengthNull"] = f"{audit['null_mean'] * 100:.1f}"
        macros["gradeLengthP"] = format_p_value(audit)
    except (ImportError, OSError, KeyError) as exc:
        print(f"  corpus length audit unavailable: {exc}")

    # What the star design bought. Reported so the design choice is a stated
    # trade rather than an unexplained omission of interactions.
    factorial_arms = 3 * len(("scripted", "bounded", "free")) * 3 * len(CREW_DEPLOYMENTS)
    macros["numFactorialArms"] = str(factorial_arms)
    macros["numFactorialCells"] = f"{factorial_arms * 48 * 2:,}"

    # ---------------------------------------------------------------- grades --
    ordinal: dict[str, Any] | None = None
    try:
        ordinal = evaluate_ordinal_leakage(
            adaptive, seed=args.seed, n_perm=max(args.permutations, 400)
        )
    except ValueError as exc:
        print(f"  graded ladder unevaluable: {exc}")
    if ordinal:
        report["ordinal"] = ordinal
        macros["gradeSomersD"] = f"{ordinal['somers_d']:.3f}"
        macros["gradeSomersDSigned"] = f"{ordinal['somers_d_signed']:+.3f}"
        macros["gradeTrendZ"] = f"{ordinal['trend']['z']:+.1f}"
        macros["gradeDirection"] = ordinal["direction"]
        if "null" in ordinal and "p_value" in ordinal["null"]:
            macros["gradeNull"] = f"{ordinal['null']['null_mean']:.3f}"
            macros["gradeP"] = format_p_value(ordinal["null"])
        within = ordinal.get("within_sensitive") or {}
        if "somers_d" in within:
            macros["gradeWithinSomersD"] = f"{within['somers_d']:.3f}"
            macros["gradeWithinSomersDSigned"] = f"{within['somers_d_signed']:+.3f}"
            macros["gradeWithinTrendZ"] = f"{within['trend']['z']:+.1f}"
            # Consumed by the manuscript so the direction is typeset from the
            # data rather than from an author's memory of which way it went.
            macros["gradeWithinDirection"] = within["direction"]
            if "null" in within and "p_value" in within["null"]:
                macros["gradeWithinNull"] = f"{within['null']['null_mean']:.3f}"
                macros["gradeWithinP"] = format_p_value(within["null"])
                family["grade:within-sensitive trend"] = within["null"]["p_value"]
        macros["gradeRungs"] = str(len(ordinal["rungs"]))
    mechanism = _rung_mechanism(adaptive)
    report["rung_mechanism"] = {str(k): v for k, v in mechanism.items()}
    if len(mechanism) >= 4:
        egress = [mechanism[r]["egress"] for r in sorted(mechanism)]
        depth = [mechanism[r]["depth"] for r in sorted(mechanism)]
        # Stated as macros so the prose cannot describe a shape the data does not
        # have. "saturating" is the case where the sensitive rungs are flat or
        # falling relative to each other while all sit above rung 0.
        macros["gradeEgressShape"] = (
            "monotone"
            if egress == sorted(egress)
            else "saturating"
            if min(egress[1:]) > egress[0]
            else "non-monotone"
        )
        # Prose-ready: the shared depth when the ladder is saturated, or the
        # observed span when it is not. A bare "yes"/"no" reads badly inline.
        macros["gradeDepthSpan"] = (
            f"{depth[0]:.0f} at every rung"
            if len(set(depth)) == 1
            else f"{min(depth):.0f}--{max(depth):.0f} across rungs"
        )
        macros["gradeEgressRoutine"] = f"{egress[0]:.0f}"
        macros["gradeEgressPeak"] = f"{max(egress):.0f}"
        macros["gradeEgressTop"] = f"{egress[-1]:.0f}"
    tables["tab_grades"] = _grade_table(ordinal, mechanism)

    # -------------------------------------------------------------- autonomy --
    autonomy_journal = load("autonomy")
    autonomy_rows = [
        ("scripted", *measure(structure)),
        ("bounded", *measure(adaptive)),
        ("free", *measure(_records_for(autonomy_journal, "adaptive", autonomy="free"))),
    ]
    for label, attr, memb in autonomy_rows:
        if attr and "p_value" in attr:
            family[f"autonomy:{label}:attribute"] = attr["p_value"]
        if memb and "p_value" in memb:
            family[f"autonomy:{label}:membership"] = memb["p_value"]
    report["autonomy"] = {
        label: {"attribute": attr, "membership": memb}
        for label, attr, memb in autonomy_rows
    }

    # ---------------------------------------------------------- architecture --
    arch_journal = load("architecture")
    arch_rows = [("pipeline crew", *measure(adaptive))]
    for slug, label in (
        ("hierarchical_supervisor", "hierarchical supervisor"),
        ("react_single_agent", "single-agent ReAct"),
    ):
        arch_rows.append(
            (label, *measure(_records_for(arch_journal, "adaptive", architecture=slug)))
        )
    for label, attr, memb in arch_rows:
        if attr and "p_value" in attr:
            family[f"architecture:{label}:attribute"] = attr["p_value"]
        if memb and "p_value" in memb:
            family[f"architecture:{label}:membership"] = memb["p_value"]
    report["architecture"] = {
        label: {"attribute": attr, "membership": memb}
        for label, attr, memb in arch_rows
    }

    # ------------------------------------------------------------ crew model --
    # The model axis is three *homogeneous* crews, and deliberately does not
    # include the baseline: the baseline runs a heterogeneous crew (a fast
    # deployment for intake/review, a deeper one for extraction), so no
    # baseline cell belongs to any single-deployment arm. Comparing a
    # homogeneous arm against the mixed baseline would confound "which model"
    # with "one model or two", so the three arms are compared only with each
    # other and the manuscript must say so.
    model_journal = load("model")
    model_pool = _records_for(model_journal, "adaptive")
    mixed_baseline = len(adaptive) - len(
        [r for d in CREW_DEPLOYMENTS for r in _by_model(adaptive, d)]
    )
    report["model_note"] = {
        "arms": "homogeneous single-deployment crews",
        "baseline_excluded_rows": mixed_baseline,
        "why": (
            "the baseline crew is heterogeneous, so it belongs to no "
            "single-deployment arm; the three arms are compared only with each other"
        ),
    }
    model_rows = []
    for deployment in CREW_DEPLOYMENTS:
        model_rows.append((deployment, *measure(_by_model(model_pool, deployment))))
    for label, attr, memb in model_rows:
        if attr and "p_value" in attr:
            family[f"model:{label}:attribute"] = attr["p_value"]
        if memb and "p_value" in memb:
            family[f"model:{label}:membership"] = memb["p_value"]
    report["model"] = {
        label: {"attribute": attr, "membership": memb}
        for label, attr, memb in model_rows
    }

    # Emitted unconditionally. A macro the manuscript references must exist or
    # the paper does not build, and "the arm was not measurable" is information
    # the reader should get rather than a LaTeX error -- or worse, a sentence
    # silently dropped from a rebuild.
    # Depth saturation per model arm. This is the mechanism behind the model
    # axis and it is visible in one histogram: the deployment whose research
    # depth still varies leaks far more than the ones pinned at the cap.
    cap = None
    depth_share: dict[str, float] = {}
    for deployment in CREW_DEPLOYMENTS:
        sub = _by_model(model_pool, deployment)
        if not sub:
            continue
        depths = [
            int(_features(record["trace"], include_bigrams=False).get("hop_count", 0))
            for record in sub
        ]
        cap = max(cap or 0, max(depths))
        depth_share[deployment] = 100.0 * sum(1 for d in depths if d >= 7) / len(depths)
    if depth_share:
        report["model_depth_at_cap_pct"] = depth_share
        low = min(depth_share, key=lambda k: depth_share[k])
        macros["modelVariedName"] = low
        macros["modelVariedCapPct"] = f"{depth_share[low]:.0f}"
        others = [v for k, v in depth_share.items() if k != low]
        if others:
            macros["modelSaturatedCapPct"] = f"{min(others):.0f}--{max(others):.0f}"

    # ------------------------------------------------------------------ #
    # The finite-epsilon frontier, per crew-model arm.
    #
    # The graded mechanism buckets research depth into published templates.
    # Whether it has anything to release therefore depends on whether that
    # coordinate is still live: on a deployment pinned at the hop cap the
    # partition is degenerate and the mechanism is vacuous. Reporting the
    # headline arm alone hid that dependence; reporting every arm with its
    # occupancy and regime label makes the precondition itself the result.
    #
    # The partition is fixed to the *declared* public templates and is never
    # adapted to the observed depth support. The partition is the release
    # alphabet: choosing it from the corpus would make the alphabet a function
    # of private data, so a neighbouring corpus could induce a different
    # alphabet and Proposition prop:rr would stop applying -- the epsilon
    # printed would not be the epsilon spent.
    frontier_rows: list[tuple[str, dict[str, Any]]] = []
    for deployment in CREW_DEPLOYMENTS:
        sub = _by_model(model_pool, deployment)
        if len(sub) < 24:
            continue
        try:
            frontier_rows.append(
                (
                    deployment,
                    randomized_response_frontier(
                        sub, target="attribute", seed=args.seed + 404
                    ),
                )
            )
        except Exception as exc:  # noqa: BLE001 - report, never fabricate
            print(f"  note: frontier unavailable for {deployment}: {exc}")
    if frontier_rows:
        report["frontier_arms"] = {
            name: {
                "templates_occupied": fr.get("templates_occupied"),
                "sample_occupies_all_templates": fr.get(
                    "sample_occupies_all_templates"
                ),
                "boundaries": fr.get("boundaries"),
                "rows": fr.get("rows"),
            }
            for name, fr in frontier_rows
        }
        epsilons = [row["epsilon"] for row in frontier_rows[0][1]["rows"]]
        header = (
            "$\\varepsilon$ & keep & "
            + " & ".join(
                "\\textsc{" + n.replace("_", "-") + "}" for n, _ in frontier_rows
            )
            + "\\\\\n"
        )
        body_lines = []
        for index, eps in enumerate(epsilons):
            keep = frontier_rows[0][1]["rows"][index]["keep_probability"]
            cells = [
                _auc3(fr["rows"][index]["auc_mean"]) for _, fr in frontier_rows
            ]
            body_lines.append(
                f"{eps:g} & {keep:.2f} & " + " & ".join(cells) + "\\\\"
            )
        occ = [
            f"{fr.get('templates_occupied') or 0}/3" for _, fr in frontier_rows
        ]
        body_lines.append("\\midrule")
        body_lines.append(
            "\\multicolumn{2}{@{}l}{templates occupied} & "
            + " & ".join(occ)
            + "\\\\"
        )
        tables["tab_frontier_arms"] = _wrap(
            4,
            "rr" + "c" * len(frontier_rows),
            header,
            "\n".join(body_lines),
        )

        # Foreground the arm whose released statistic actually has support.
        # The selection rule is a property of the mechanism and is declared
        # before the numbers: the mechanism is evaluable iff its bucketed
        # statistic is non-degenerate. Every arm is published either way, two
        # of them labelled vacuous, so the table forecloses a cherry-pick
        # reading rather than inviting one.
        lo, hi = PUBLISHED_DEPTH_RANGE
        width = (hi - lo) / 3.0
        edges = (lo + width, lo + 2 * width)

        def _band(depth: int) -> int:
            return 0 if depth < edges[0] else (1 if depth < edges[1] else 2)

        shares: dict[str, float] = {}
        for name, _fr in frontier_rows:
            depths = [
                int(_features(r["trace"], include_bigrams=False).get("hop_count", 0))
                for r in _by_model(model_pool, name)
            ]
            shares[name] = (
                100.0
                * max(sum(1 for d in depths if _band(d) == b) for b in (0, 1, 2))
                / len(depths)
            )
        report["frontier_top_band_pct"] = shares

        informative = [
            (name, fr)
            for name, fr in frontier_rows
            if fr.get("sample_occupies_all_templates") and shares[name] < 85.0
        ]
        informative_names = {name for name, _ in informative}
        saturated = [name for name, _ in frontier_rows if name not in informative_names]
        macros["frontierSatNames"] = (
            ", ".join(n.replace("_", "-") for n in saturated) if saturated else "--"
        )
        macros["frontierSatRegime"] = "vacuous" if saturated else "--"
        if saturated:
            sat_hi = [
                fr["rows"][0]["auc_mean"]
                for n, fr in frontier_rows
                if n in saturated
            ]
            sat_lo = [
                fr["rows"][-1]["auc_mean"]
                for n, fr in frontier_rows
                if n in saturated
            ]
            macros["frontierSatHiAttr"] = (
                f"{min(sat_hi):.2f}--{max(sat_hi):.2f}"
                if len(sat_hi) > 1
                else f"{sat_hi[0]:.2f}"
            )
            macros["frontierSatLoAttr"] = (
                f"{min(sat_lo):.2f}--{max(sat_lo):.2f}"
                if len(sat_lo) > 1
                else f"{sat_lo[0]:.2f}"
            )
        for macro in (
            "frontierArmName", "frontierArmBands", "frontierArmTopBand",
            "frontierArmRegime", "frontierArmHiEps", "frontierArmHiAttr",
            "frontierArmLoEps", "frontierArmLoAttr", "frontierArmSpread",
        ):
            macros.setdefault(macro, "--")
        if informative:
            name, fr = max(
                informative, key=lambda item: item[1]["rows"][0]["auc_mean"]
            )
            rows = fr["rows"]
            macros["frontierArmName"] = name.replace("_", "-")
            macros["frontierArmBands"] = str(fr.get("templates_occupied") or 0)
            macros["frontierArmTopBand"] = f"{shares[name]:.0f}"
            macros["frontierArmRegime"] = "informative"
            macros["frontierArmHiEps"] = f"{rows[0]['epsilon']:g}"
            macros["frontierArmHiAttr"] = _auc3(rows[0]["auc_mean"])
            macros["frontierArmLoEps"] = f"{rows[-1]['epsilon']:g}"
            macros["frontierArmLoAttr"] = _auc3(rows[-1]["auc_mean"])
            macros["frontierArmSpread"] = _auc3(
                rows[0]["auc_mean"] - rows[-1]["auc_mean"]
            )

    measured_models = [(label, attr) for label, attr, _ in model_rows if attr]
    macros["modelCount"] = str(len(measured_models))
    macros.setdefault("modelOrdering", "--")
    for name in ("modelContrastDelta", "modelContrastCI",
                 "modelContrastHigh", "modelContrastLow", "modelContrastGroups"):
        macros.setdefault(name, "--")
    if len(measured_models) >= 2:
        ordering = sorted(measured_models, key=lambda item: item[1]["auc"], reverse=True)
        macros["modelOrdering"] = ", ".join(label for label, _ in ordering)
        macros["modelTopAttr"] = _auc3(ordering[0][1]["auc"])
        macros["modelMidAttr"] = _auc3(ordering[len(ordering) // 2][1]["auc"])
        macros["modelLowAttr"] = _auc3(ordering[-1][1]["auc"])
        membs = [
            m for _, _, m in model_rows if m and m.get("auc") is not None
        ]
        if membs:
            macros["modelMembRange"] = (
                f"{min(m['auc'] for m in membs):.3f}--{max(m['auc'] for m in membs):.3f}"
            )
            nulls_seen = [m.get("null_mean") for m in membs if m.get("null_mean")]
            if nulls_seen:
                macros["modelMembNull"] = _auc2(sum(nulls_seen) / len(nulls_seen))
        # The one pre-declared contrast: weakest vs strongest deployment,
        # paired per held-out group. Three points cannot carry a scaling law.
        low, high = ordering[-1][0], ordering[0][0]
        try:
            contrast = paired_group_difference(
                _by_model(model_pool, high),
                _by_model(model_pool, low),
                target="attribute",
                n_bootstrap=2000,
                seed=args.seed,
            )
            report["model_contrast"] = {"high": high, "low": low, **contrast}
            macros["modelContrastDelta"] = f"{contrast['mean_difference']:+.3f}"
            lo, hi = contrast["ci95"]
            macros["modelContrastCI"] = f"[{lo:+.3f}, {hi:+.3f}]"
            macros["modelContrastHigh"] = high
            macros["modelContrastLow"] = low
            macros["modelContrastGroups"] = str(contrast["n_groups"])
        except ValueError as exc:
            # KeyError is deliberately NOT caught: a renamed field in
            # paired_group_difference must fail loudly here rather than
            # degrade to "unevaluable" and silently drop the contrast macros
            # after a multi-hour run. This exact bug was caught that way.
            print(f"  model contrast unevaluable: {exc}")

    # Per-arm macros for the arms the manuscript names in prose. Only these
    # three: the paper compares the topologies explicitly, and a hardcoded
    # 0.760 in that sentence is the same drift the generated macros exist to
    # prevent.
    for label, key in (
        ("pipeline crew", "archPipelineAttr"),
        ("hierarchical supervisor", "archHierAttr"),
        ("single-agent ReAct", "archReactAttr"),
    ):
        row = next((a for name, a, _ in arch_rows if name == label), None)
        if row:
            macros[key] = _auc3(row["auc"])
            macros[key + "P"] = format_p_value(row) if "p_value" in row else "=--"

    tables["tab_factors"] = _combined_factor_table(
        [
            ("Autonomy", autonomy_rows),
            ("Topology", arch_rows),
            ("Crew model", model_rows),
        ]
    )

    # ----------------------------------------------- multiple comparisons ----
    if family:
        corrected = holm_bonferroni(family, alpha=0.05)
        report["holm"] = corrected
        macros["holmFamilySize"] = str(corrected["family_size"])
        results = corrected["results"]
        macros["holmRejected"] = str(
            sum(1 for entry in results.values() if entry["rejected"])
        )
        # Holm's smallest threshold is alpha/m, so a permutation test can only
        # place an arm on the right side of it if it can report a p-value that
        # small with some precision. The floor is 1/(n_perm+1), and near it the
        # estimate is noisy: at 400 draws one arm reported p=0.005 (adjusted
        # 0.055, marginal) where 2000 draws gave p=0.0015 (adjusted 0.012,
        # rejected). Reporting a marginal list computed below that resolution
        # would present a permutation artifact as a finding, so it is refused.
        required = int(len(family) / corrected["alpha"]) + 1
        macros["holmPerms"] = str(args.permutations)
        macros["holmPermsRequired"] = str(required)
        if args.permutations < required:
            print(
                f"  WARNING: {args.permutations} permutations cannot resolve a "
                f"{len(family)}-hypothesis Holm family at alpha="
                f"{corrected['alpha']}; {required} are needed. The "
                "marginal-arm list is withheld rather than reported at this "
                "resolution."
            )
            macros["holmMarginalCount"] = "--"
            macros["holmMarginalList"] = (
                f"withheld: {args.permutations} permutations cannot resolve this "
                f"family (needs {required})"
            )
            marginal = None
        # Arms that clear their own null but not the family correction. These
        # are the ones prose most easily overstates: "clears its null" and
        # "survives correction" are different claims, and with a 13-hypothesis
        # family an arm at p=0.011 lands at 0.055 adjusted.
        else:
            marginal = sorted(
                (name for name, e in results.items()
                 if not e["rejected"] and e["p_value"] < 0.05),
                key=lambda n: results[n]["p_value"],
            )
            macros["holmMarginalCount"] = str(len(marginal))
            macros["holmMarginalList"] = (
            "; ".join(
                f"{n.replace(':', ' ')} ($p={results[n]['p_value']:.3f}$, "
                f"adjusted ${results[n]['p_adjusted']:.3f}$)"
                for n in marginal
            )
                or "none"
            )

    # Completed cells only. A journal also carries rows for cells that failed
    # and were retried, so counting every row overstates the study -- and this
    # number appears in the abstract. The model spoke alone holds 180 such rows
    # from a run-id collision that was fixed and re-run.
    # The in-CVM replication is a separate journal on purpose: it re-runs the
    # baseline arm cell-for-cell, so pooling it would double-count those cells
    # in \matrixCells -- a number that appears in the abstract and in a
    # sentence saying the study was not re-run on the VM. It gets its own
    # macros instead.
    star_paths = [
        path
        for path in sorted(args.journal_dir.glob("matrix-*.jsonl"))
        if path.name not in STAR_EXCLUDED_JOURNALS
    ]
    completed = 0
    attempted = 0
    for path in star_paths:
        for row in load_experiment_records(path):
            attempted += 1
            if row.get("status") in (None, "completed"):
                completed += 1
    report["cells"] = {"completed": completed, "journalled_rows": attempted}
    macros["matrixCells"] = str(completed)

    # WHERE the cells executed, from the journal rather than from memory. The
    # first draft of the generality section claimed all cells "run live inside
    # the confidential VM"; they did not -- they ran on the artifact host
    # against the same Azure deployments, and the journals carry no attestation
    # provenance at all. The paper keeps the attested deployment and the
    # empirical study separate on purpose, and a hand-written sentence had
    # already broken that separation once.
    attested = 0
    for path in star_paths:
        for row in load_experiment_records(path):
            att = (row.get("provenance") or {}).get("attestation") or {}
            if att.get("hardware_backed") and att.get("verdict") == "verified":
                attested += 1
    macros["matrixAttestedCells"] = str(attested)

    # The in-CVM replication, counted and described separately.
    cvm_completed = 0
    cvm_attested = 0
    cvm_measurements: set[str] = set()
    for name in sorted(STAR_EXCLUDED_JOURNALS):
        path = args.journal_dir / name
        if not path.is_file():
            continue
        for row in load_experiment_records(path):
            if row.get("status") not in (None, "completed"):
                continue
            cvm_completed += 1
            att = (row.get("provenance") or {}).get("attestation") or {}
            if att.get("hardware_backed") and att.get("verdict") == "verified":
                cvm_attested += 1
                measurement = att.get("launch_measurement")
                if measurement:
                    cvm_measurements.add(str(measurement))
    macros["matrixCvmCells"] = str(cvm_completed)
    macros["matrixCvmAttestedCells"] = str(cvm_attested)
    macros["matrixCvmLaunchMeasurement"] = (
        sorted(cvm_measurements)[0][:16] if len(cvm_measurements) == 1 else "--"
    )
    macros["matrixCvmBoots"] = str(len(cvm_measurements))
    report["cvm"] = {
        "completed": cvm_completed,
        "attested": cvm_attested,
        "launch_measurements": sorted(cvm_measurements),
    }
    if cvm_completed and cvm_attested != cvm_completed:
        print(
            f"  WARNING: {cvm_completed - cvm_attested} of {cvm_completed} in-CVM "
            "rows lack a verified hardware attestation"
        )

    # The paired host-vs-CVM comparison. Cell keys are byte-identical by
    # construction, so this differences the same case at the same seed under the
    # same crew and isolates the execution environment alone. Reported paired
    # per held-out group with a cluster bootstrap of the difference, because
    # per-arm CIs overlapping says nothing about whether the arms differ.
    cvm_journal = args.journal_dir / "matrix-cvm.jsonl"
    host_journal = args.journal_dir / "matrix-baseline.jsonl"
    if cvm_completed and cvm_journal.is_file() and host_journal.is_file():
        cvm_pool = load_experiment_records(cvm_journal)
        host_pool = load_experiment_records(host_journal)
        locus_rows: list[tuple[str, str, dict[str, Any], dict[str, Any]]] = []
        for condition in ("adaptive", "structure", "full"):
            host_recs = _records_for(host_pool, condition)
            cvm_recs = _records_for(cvm_pool, condition)
            if not host_recs or not cvm_recs:
                continue
            for target in ("attribute", "membership"):
                entry: dict[str, Any] = {}
                for label, recs in (("host", host_recs), ("cvm", cvm_recs)):
                    try:
                        entry[label] = evaluate_attack(
                            recs, target=target, seed=args.seed
                        )["auc"]
                    except Exception as exc:  # noqa: BLE001
                        entry[f"{label}_error"] = str(exc)
                if args.permutations:
                    try:
                        paired = paired_group_difference(
                            host_recs,
                            cvm_recs,
                            target=target,
                            seed=args.seed,
                            n_bootstrap=args.permutations,
                        )
                        entry["difference"] = paired["mean_difference"]
                        entry["ci95"] = paired["ci95"]
                    except Exception as exc:  # noqa: BLE001
                        entry["paired_error"] = str(exc)
                locus_rows.append((condition, target, entry, {}))
        report["cvm_vs_host"] = {
            f"{cond}:{target}": entry for cond, target, entry, _ in locus_rows
        }

        header = (
            "Arm & Secret & host & in-CVM & paired $\\Delta$ (95\\% CI) \\\\\n"
        )
        body = []
        for cond, target, entry, _ in locus_rows:
            host_auc = entry.get("host")
            cvm_auc = entry.get("cvm")
            delta = entry.get("difference")
            ci = entry.get("ci95")
            delta_text = "--"
            if delta is not None and ci:
                # Inclusive: full padding gives a degenerate CI of exactly
                # [0, 0] around a zero difference, which means the two arms
                # are identical -- the enforcement result -- and must not be
                # starred as a significant difference.
                crosses = ci[0] <= 0 <= ci[1]
                delta_text = (
                    f"${delta:+.3f}$ [{ci[0]:+.3f}, {ci[1]:+.3f}]"
                    + ("" if crosses else "$^{*}$")
                )
            body.append(
                f"{cond} & {target} & "
                f"{'--' if host_auc is None else _auc3(host_auc)} & "
                f"{'--' if cvm_auc is None else _auc3(cvm_auc)} & {delta_text} \\\\"
            )
        tables["tab_locus"] = _wrap(4, "llccl", header, "\n".join(body))

        # The headline sentence's numbers, generated rather than transcribed.
        for cond, target, entry, _ in locus_rows:
            if cond != "adaptive":
                continue
            key = "Attr" if target == "attribute" else "Member"
            if entry.get("cvm") is not None:
                macros[f"cvm{key}AUC"] = _auc3(entry["cvm"])
            if entry.get("difference") is not None and entry.get("ci95"):
                macros[f"cvm{key}Delta"] = f"{entry['difference']:+.3f}"
                macros[f"cvm{key}CI"] = (
                    f"{entry['ci95'][0]:+.3f}, {entry['ci95'][1]:+.3f}"
                )
        # How many of the paired contrasts are indistinguishable from zero.
        indistinguishable = sum(
            1
            for _, _, entry, _ in locus_rows
            if entry.get("ci95") and entry["ci95"][0] <= 0 <= entry["ci95"][1]
        )
        macros["cvmPairedTotal"] = str(len(locus_rows))
        macros["cvmPairedIndistinguishable"] = str(indistinguishable)
    # Phrased here rather than in the manuscript, so the sentence stays correct
    # in all three cases without an author choosing between them.
    macros["matrixAttestedNote"] = (
        "None of them carry hardware attestation provenance"
        if attested == 0
        else "Every one of them carries hardware attestation provenance"
        if attested == completed
        else f"{attested} of the {completed} carry hardware attestation provenance"
    )
    macros["matrixHost"] = (
        "inside the attested confidential VM"
        if attested == completed and completed
        else "on the artifact host, against the same Azure deployments"
        if attested == 0
        else f"on a mix of hosts ({attested} of {completed} cells attested)"
    )
    if attempted != completed:
        print(
            f"  note: {attempted - completed} journalled rows are failed "
            "attempts and are excluded from \\matrixCells"
        )
    if args.permutations:
        macros["matrixNPerm"] = str(args.permutations)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for name, body in tables.items():
        (args.out_dir / f"{name}.tex").write_text(
            body if body.startswith("%") else TABLE_HEADER + body + "\n", encoding="utf-8"
        )
    merge_macros(args.out_dir / "macros.tex", macros, MACRO_HEADER)
    if args.report:
        args.report.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")

    print(f"wrote {len(tables)} tables and {len(macros)} macros -> {args.out_dir}")
    for name, rows in (
        ("autonomy", autonomy_rows), ("architecture", arch_rows), ("model", model_rows)
    ):
        print(f"  {name}: {sum(1 for _, a, _ in rows if a)}/{len(rows)} arms measurable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
