"""Cross-family artifacts: does the trace channel survive a change of task?

The generality sweep varied autonomy, topology and crew model but held the task
fixed, so a reviewer can reasonably ask whether the channel is a property of
agents or of prior authorization. This compares the two task families and, more
importantly, uses their *polarity inversion* to separate two readings of the
mechanism that the prior-authorization corpus alone cannot distinguish.

In prior authorization the sensitive rungs are the ones with **missing**
documentation, so "harder case" is confounded with "less complete file". In AML
alert triage the sensitive rungs carry **more** evidence of a worse thing, so
the top rung is the best-evidenced case. Two readings follow:

  * If the channel appears in **both** families, it tracks adjudication
    difficulty -- the agent does more work on cases that are harder to decide,
    whichever direction the evidence runs.
  * If it appears **only** in prior authorization, it tracks documentation
    absence, and the paper's causal sentence is wrong.

Every number is reported against the family's own calibrated within-group
permutation null, never against 0.5: the protocol selects max(A1, A2) by fold
mean and reports an inversion-safe max(AUC, 1-AUC), so the null floor sits near
0.58-0.60 rather than at chance.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from make_paper_artifacts import (  # noqa: E402
    _auc3,
    _records_for,
    _wrap,
    format_p_value,
    merge_macros,
)

from traceguard.attack import (  # noqa: E402
    evaluate_attack,
    evaluate_ordinal_leakage,
    holm_bonferroni,
    permutation_null,
)
from traceguard.attack import extract_trace_features as _features  # noqa: E402
from traceguard.experiment import load_experiment_records  # noqa: E402

TABLE_HEADER = (
    "% Generated by scripts/make_family_artifacts.py from the per-family "
    "journals.\n"
)
MACRO_HEADER = (
    "% Cross-family macros generated by scripts/make_family_artifacts.py.\n"
)

# Display names, and the direction the sensitivity ladder runs in each family.
FAMILIES = {
    "prior-authorization": ("prior authorization", "documentation absent"),
    "aml-alert-triage": ("AML alert triage", "evidence present"),
}


def _by_domain(records: list[dict[str, Any]], domain: str) -> list[dict[str, Any]]:
    return [r for r in records if r.get("domain") == domain]


def _depth_profile(records: list[dict[str, Any]]) -> dict[str, Any]:
    depths = [
        int(_features(r["trace"], include_bigrams=False).get("hop_count", 0))
        for r in records
    ]
    if not depths:
        return {}
    return {
        "median": sorted(depths)[len(depths) // 2],
        "min": min(depths),
        "max": max(depths),
        "at_cap_pct": 100.0 * sum(1 for d in depths if d >= 7) / len(depths),
    }


def _arm(records: list[dict[str, Any]], *, seed: int, n_perm: int) -> dict[str, Any]:
    """Both secrets on one arm, each against its own calibrated null."""

    out: dict[str, Any] = {}
    for target in ("attribute", "membership"):
        try:
            result = evaluate_attack(records, target=target, seed=seed)
        except Exception as exc:  # noqa: BLE001 - report, never fabricate
            out[target] = {"error": str(exc)}
            continue
        entry = {"auc": result["auc"], "n": len(records)}
        if n_perm:
            null = permutation_null(
                records, target=target, n_perm=n_perm, seed=seed
            )
            entry.update(
                {
                    "null_mean": null["null_mean"],
                    "null_q95": null["null_q95"],
                    "p_value": null["p_value"],
                    # format_p_value needs n_perm to render the floor as
                    # "<1/(n+1)" instead of a misleading "=0.000".
                    "null_report": {
                        "n_perm": null.get("n_perm", n_perm),
                        "p_value": null["p_value"],
                    },
                }
            )
        out[target] = entry
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--journal-dir", type=Path, default=ROOT / "artifacts",
        help="directory holding the per-family journals",
    )
    ap.add_argument("--out-dir", type=Path, default=ROOT / "tables")
    ap.add_argument("--seed", type=int, default=20260710)
    ap.add_argument(
        "--permutations", type=int, default=2000,
        help="calibrated within-group permutation draws per arm",
    )
    ap.add_argument("--report", type=Path)
    args = ap.parse_args(argv)

    # Prior authorization comes from the headline arm; the second family from
    # its own journal. Never pooled -- separate corpora, separate digests.
    sources = {
        "prior-authorization": args.journal_dir / "matrix-baseline.jsonl",
        "aml-alert-triage": args.journal_dir / "family-aml.jsonl",
    }
    rows: dict[str, list[dict[str, Any]]] = {}
    for domain, path in sources.items():
        if not path.is_file():
            print(f"  note: {path.name} absent; skipping {domain}")
            continue
        rows[domain] = load_experiment_records(path)

    if len(rows) < 2:
        print(
            "cross-family comparison needs both journals; "
            f"have {sorted(rows)}. Nothing written."
        )
        return 0

    report: dict[str, Any] = {"seed": args.seed, "permutations": args.permutations}
    macros: dict[str, str] = {}
    family_rows: list[tuple[str, dict[str, Any], dict[str, Any]]] = []
    pvalues: dict[str, float] = {}

    for domain, (display, polarity) in FAMILIES.items():
        if domain not in rows:
            continue
        adaptive = _by_domain(_records_for(rows[domain], "adaptive"), domain)
        if not adaptive:
            # An archived journal predating the domain label defaults to prior
            # authorization, which is correct -- but be explicit about it.
            adaptive = _records_for(rows[domain], "adaptive")
        arm = _arm(adaptive, seed=args.seed, n_perm=args.permutations)
        depth = _depth_profile(adaptive)
        family_rows.append((domain, arm, depth))
        report[domain] = {
            "display_name": display,
            "ladder_polarity": polarity,
            "n": len(adaptive),
            "arm": arm,
            "depth": depth,
        }
        for target in ("attribute", "membership"):
            entry = arm.get(target) or {}
            if "p_value" in entry:
                pvalues[f"family:{domain}:{target}"] = entry["p_value"]

        # The ordinal claim, restricted to the non-zero rungs. On a graded
        # ladder a step function is monotone, so the full ladder reads large
        # whenever rung 0 separates from the rest; the incremental claim is the
        # one restricted to the sensitive rungs.
        try:
            ordinal = evaluate_ordinal_leakage(
                adaptive, seed=args.seed, n_perm=args.permutations
            )
            report[domain]["ordinal"] = ordinal
        except Exception as exc:  # noqa: BLE001
            report[domain]["ordinal"] = {"error": str(exc)}

    if pvalues:
        corrected = holm_bonferroni(pvalues, alpha=0.05)
        report["holm"] = corrected

    # ------------------------------------------------------------------ #
    # The table: both families, both secrets, each against its own null.
    # ------------------------------------------------------------------ #
    header = (
        "Task family & Ladder & $n$ & Attribute (null) & Membership (null) "
        "& depth \\\\\n"
    )
    body = []
    for domain, arm, depth in family_rows:
        display, polarity = FAMILIES[domain]
        cells = []
        for target in ("attribute", "membership"):
            entry = arm.get(target) or {}
            if "auc" not in entry:
                cells.append("--")
                continue
            null = entry.get("null_mean")
            _ = entry.get("p_value")
            text = _auc3(entry["auc"])
            if null is not None:
                text += f" ({_auc3(null)})"
            if entry.get("null_report") is not None:
                text += f"$^{{p{format_p_value(entry['null_report'])}}}$"
            cells.append(text)
        depth_text = (
            f"{depth['median']} [{depth['min']}--{depth['max']}]" if depth else "--"
        )
        n = (arm.get("attribute") or {}).get("n", 0)
        body.append(
            f"\\emph{{{display}}} & {polarity} & {n} & "
            f"{cells[0]} & {cells[1]} & {depth_text} \\\\"
        )
    tables = {
        "tab_families": _wrap(4, "llrccc", header, "\n".join(body))
    }

    # ------------------------------------------------------------------ #
    # Macros. The reading the inversion licenses is computed, not asserted.
    # ------------------------------------------------------------------ #
    measured = {
        domain: (arm.get("attribute") or {})
        for domain, arm, _ in family_rows
        if "auc" in (arm.get("attribute") or {})
    }
    macros["familyCount"] = str(len(family_rows))
    for domain, entry in measured.items():
        key = "Pa" if domain == "prior-authorization" else "Aml"
        macros[f"family{key}Attr"] = _auc3(entry["auc"])
        if entry.get("null_mean") is not None:
            macros[f"family{key}Null"] = _auc3(entry["null_mean"])
        if entry.get("null_report") is not None:
            macros[f"family{key}AttrP"] = format_p_value(entry["null_report"])
        macros[f"family{key}N"] = str(entry.get("n", 0))
    for domain, arm, _ in family_rows:
        key = "Pa" if domain == "prior-authorization" else "Aml"
        memb = arm.get("membership") or {}
        if "auc" in memb:
            macros[f"family{key}Member"] = _auc3(memb["auc"])
            if memb.get("null_report") is not None:
                macros[f"family{key}MemberP"] = format_p_value(memb["null_report"])

    # Which reading the data supports. Both families clearing their own nulls
    # means the channel tracks adjudication difficulty rather than
    # documentation absence -- the inversion is what makes this separable.
    cleared = [
        domain
        for domain, entry in measured.items()
        if entry.get("p_value") is not None and entry["p_value"] < 0.05
    ]
    macros["familyBothLeak"] = "yes" if len(cleared) == len(measured) else "no"

    # Holm across the cross-family hypotheses, and the ordinal gradation, so
    # the paper does not have to transcribe either.
    if pvalues:
        results = corrected.get("results", {})
        rejected = [k for k, v in results.items() if v.get("rejected")]
        macros["familyHolmSize"] = str(corrected.get("family_size", len(pvalues)))
        macros["familyHolmRejected"] = str(len(rejected))
        memb_reject = [k for k in rejected if k.endswith(":membership")]
        macros["familyMemberReplicates"] = (
            "yes" if len(memb_reject) == len(family_rows) else "no"
        )
    for domain, _arm_unused, _depth in family_rows:
        key = "Pa" if domain == "prior-authorization" else "Aml"
        ordinal = (report.get(domain) or {}).get("ordinal") or {}
        if ordinal.get("somers_d") is not None:
            macros[f"family{key}SomersD"] = f"{ordinal['somers_d']:.3f}"
    macros["familyReading"] = (
        "adjudication difficulty"
        if len(cleared) == len(measured) and len(measured) > 1
        else "documentation absence"
        if cleared and len(cleared) < len(measured)
        else "--"
    )
    report["families_clearing_own_null"] = cleared

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in tables.items():
        (args.out_dir / f"{name}.tex").write_text(
            TABLE_HEADER + text + "\n", encoding="utf-8"
        )
    merge_macros(args.out_dir / "macros.tex", macros, MACRO_HEADER)
    if args.report:
        args.report.write_text(
            json.dumps(report, indent=2, default=str), encoding="utf-8"
        )
    print(f"wrote {len(tables)} tables and {len(macros)} macros -> {args.out_dir}")
    for domain, arm, _ in family_rows:
        attr = (arm.get("attribute") or {}).get("auc")
        memb = (arm.get("membership") or {}).get("auc")
        print(
            f"  {FAMILIES[domain][0]:22s} attribute="
            f"{attr if attr is None else f'{attr:.3f}'}  membership="
            f"{memb if memb is None else f'{memb:.3f}'}"
        )
    print(f"  reading supported: {macros['familyReading']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
