#!/usr/bin/env python3
r"""Why doubling the groups did not tighten the paired contrast.

Extending the corpus from twelve independent groups to twenty-four was supposed
to halve the standard error and take the paired minimum detectable effect toward
0.05. It did not: the MDE rose. This emits the numbers that say why, because the
explanation is a finding about the design rather than an excuse for it.

MDE $=(t_{0.975}+t_{0.80})\,\mathrm{sd}/\sqrt{n}$. Doubling $n$ shrinks
$1/\sqrt{n}$ by $\sqrt{2}$, but the twelve added domains are markedly more
heterogeneous in how much padding helps them, so sd grew by more than that. The
mean effect meanwhile replicated to three decimals, which is the part that
matters for the claim: the effect is stable and its \emph{magnitude} is
domain-dependent, exactly as the carriage account of the padded arm predicts.

Run:  python3 scripts/make_iclr_heterogeneity.py
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from make_paper_artifacts import assert_macro_names_are_latex_safe  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--twelve", type=Path,
                    default=ROOT / "iclr2027" / "tables" / "v3-power-report.json")
    ap.add_argument("--twentyfour", type=Path,
                    default=ROOT / "iclr2027" / "tables" / "v4-power-report.json")
    ap.add_argument("--macros", type=Path,
                    default=ROOT / "iclr2027" / "tables" / "macros_hetero.tex")
    args = ap.parse_args()

    a12 = json.loads(args.twelve.read_text())["attribute"]
    a24 = json.loads(args.twentyfour.read_text())["attribute"]
    shared = set(a12["groups"])
    added = [g for g in a24["groups"] if g not in shared]
    d_added = [a24["per_group_difference"][g] for g in added]
    d_shared = [a24["per_group_difference"][g] for g in a24["groups"] if g in shared]

    macros = {
        "hetGroupsLo": str(a12["n_groups"]),
        "hetGroupsHi": str(a24["n_groups"]),
        "hetDeltaLo": f"{a12['mean_difference']:+.3f}",
        "hetDeltaHi": f"{a24['mean_difference']:+.3f}",
        "hetSdLo": f"{a12['sd_difference']:.3f}",
        "hetSdHi": f"{a24['sd_difference']:.3f}",
        "hetMdeLo": f"{a12['mde']:.3f}",
        "hetMdeHi": f"{a24['mde']:.3f}",
        "hetSdRatio": f"{a24['sd_difference'] / a12['sd_difference']:.2f}",
        "hetRootTwo": f"{math.sqrt(a24['n_groups'] / a12['n_groups']):.2f}",
        "hetAddedGroups": str(len(added)),
        "hetAddedSd": f"{statistics.pstdev(d_added):.3f}",
        "hetAddedDelta": f"{statistics.mean(d_added):+.3f}",
        "hetSharedDelta": f"{statistics.mean(d_shared):+.3f}",
        "hetRangeLo": f"{min(a12['per_group_difference'].values()):+.3f}",
        "hetRangeHiLo": f"{max(a12['per_group_difference'].values()):+.3f}",
        "hetRangeHi": f"{min(a24['per_group_difference'].values()):+.3f}",
        "hetRangeHiHi": f"{max(a24['per_group_difference'].values()):+.3f}",
        # What group count the observed sd would actually require for MDE 0.05.
        "hetGroupsForTarget": str(
            int(math.ceil(((a24["t975"] + a24["t80"]) * a24["sd_difference"] / 0.05) ** 2))
        ),
    }
    assert_macro_names_are_latex_safe(list(macros))
    args.macros.write_text(
        "% Why doubling the group count did not tighten the paired contrast.\n"
        "% Generated by scripts/make_iclr_heterogeneity.py from the two power\n"
        "% reports. ICLR-scoped.\n"
        + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items())
    )
    print(f"wrote {args.macros}")
    for k, v in macros.items():
        print(f"  {k} = {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
